// English Island v0.8.0 engine regression suite
(function(){const R=[],ok=(n,v)=>R.push({name:n,pass:!!v}),D="2026-09-28";
let s=engineMigrate(null);ok("01 defaults v8",s.version===8&&s.mastery.reading===20);
let v4=engineMigrate({version:4,stars:55,mastery:{vocab:61}});ok("02 v4 preserve",v4.stars===55&&v4.mastery.vocab===61);
ok("03 v8 fields",!!s.questionHistory&&s.graceAvailable===true&&s.facilities.garden===1);
let q=enginePickDaily(s,D,12);ok("04 daily 12",q.length===12);ok("05 interleave",q.every((x,i)=>!i||x.type!==q[i-1].type));
let due=engineMigrate({version:7,reviews:[{id:"g1",due:D}]});ok("06 due included",enginePickDaily(due,D,12).some(x=>x.id==="g1"));
let w=engineApplyAnswer(s,bank.find(x=>x.id==="g2"),false,D);ok("07 wrong +1d",w.reviews.some(x=>x.id==="g2"&&x.due==="2026-09-29"));ok("08 history recorded",w.questionHistory.g2===D);
for(const [n,sm,date] of [["09 3d",30,"2026-10-01"],["10 7d",32,"2026-10-05"],["11 14d",52,"2026-10-12"],["12 30d",72,"2026-10-28"],["13 60d",82,"2026-11-27"]]){let x=engineMigrate({version:8,skillMastery:{grammar_third:sm}});x=engineApplyAnswer(x,bank.find(z=>z.id==="g2"),true,D);ok(n,x.reviews.find(r=>r.id==="g2").due===date)}
ok("14 hard",engineFeedback(s,"hard").dailyGoal===10);ok("15 fun",engineFeedback(s,"fun").dailyGoal===13);
let min={...s,dailyGoal:8};ok("16 hard floor",engineFeedback(min,"hard").dailyGoal===8);let max={...s,dailyGoal:14};ok("17 fun ceiling",engineFeedback(max,"fun").dailyGoal===14);
ok("18 quick 5",enginePickDaily(s,D,12).slice(0,5).length===5);
let recent=engineMigrate({version:8,questionHistory:{v1:"2026-09-27"}}),rq=enginePickDaily(recent,D,12);ok("19 recent suppressed",!rq.slice(0,8).some(x=>x.id==="v1"));
let st=updateStreak({...s,lastStudy:"2026-09-27",streak:3},D);ok("20 streak next day",st.streak===4);
let gr=updateStreak({...s,lastStudy:"2026-09-26",streak:3,graceAvailable:true},D);ok("21 grace",gr.streak===4&&!gr.graceAvailable);
let br=updateStreak({...s,lastStudy:"2026-09-24",streak:9},D);ok("22 streak restart",br.streak===1);
ok("23 labels",masteryLabel(95)==="Mastered"&&masteryLabel(45)==="Growing");
ok("24 facilities",facilityLevels({...s,mastery:{vocab:61,grammar:20,listening:40,reading:80}}).library===5);
ok("25 buddy preserve",engineMigrate({...s,buddy:"cat"}).buddy==="cat");
const ids=new Set(bank.map(q=>q.id)),skills=new Set(SKILL_TREE.map(s=>s.id));
ok("26 bank 200",bank.length===200);
ok("27 unique question ids",ids.size===bank.length);
ok("28 valid skill ids",bank.every(q=>skills.has(q.skill)));
ok("29 answer in choices",bank.every(q=>Array.isArray(q.c)&&q.a>=0&&q.a<q.c.length));
ok("30 explanations",bank.every(q=>typeof q.e==="string"&&q.e.length>0));
ok("31 difficulty range",bank.every(q=>q.difficulty>=1&&q.difficulty<=5));
ok("32 eiken mapping",bank.every(q=>EIKEN_LEVELS.includes(q.eiken_level)));
ok("33 skill prerequisites",SKILL_TREE.every(s=>s.prerequisite.every(p=>skills.has(p))));
ok("34 misconception ids",SKILL_TREE.every(s=>s.misconceptions.every(m=>Object.prototype.hasOwnProperty.call(MISCONCEPTIONS,m))));
ok("35 question misconception ids",bank.every(q=>(q.mis||[]).filter(Boolean).every(m=>Object.prototype.hasOwnProperty.call(MISCONCEPTIONS,m))));
const counts=bank.reduce((a,q)=>(a[q.type]=(a[q.type]||0)+1,a),{});
ok("36 domain counts",counts.vocab===60&&counts.grammar===60&&counts.listening===40&&counts.reading===40);
function acyclic(){const seen=new Set(),stack=new Set(),map=Object.fromEntries(SKILL_TREE.map(s=>[s.id,s]));function visit(id){if(stack.has(id))return false;if(seen.has(id))return true;stack.add(id);for(const p of map[id].prerequisite)if(!visit(p))return false;stack.delete(id);seen.add(id);return true}return SKILL_TREE.every(s=>visit(s.id))}
ok("37 skill tree acyclic",acyclic());
ok("38 schema complete",bank.every(q=>q.concept&&q.school_grade&&q.sibling_group&&q.question_type&&q.version===8));
let prod=enginePickDaily(s,D,12);ok("39 200-bank quest generation",prod.length===12&&new Set(prod.map(q=>q.type)).size===4);
ok("40 AI review 200",typeof AI_REVIEW!=="undefined"&&Object.keys(AI_REVIEW).length===200);
ok("41 review classes",bank.every(q=>["KEEP","REVISE","REPLACE"].includes(AI_REVIEW[q.id].status)));
ok("42 human flags",bank.every(q=>AI_REVIEW[q.id].humanRequired===(AI_REVIEW[q.id].status!=="KEEP")));
const replaced=bank.filter(q=>q.quality_revision==="v0.8.1");
ok("43 replace count 105",replaced.length===105);
ok("44 replace transfer flag",replaced.every(q=>q.transfer_check===true));
ok("45 transfer skill concept",replaced.every(q=>q.skill===q.concept&&skills.has(q.skill)));
ok("46 transfer unique prompts",new Set(replaced.map(q=>[q.type,q.q,q.sub||"",q.speech||""].join("|"))).size===replaced.length);
ok("47 choices unique",bank.every(q=>new Set(q.c).size===q.c.length));
ok("48 correct option unique",bank.every(q=>q.c.filter(x=>x===q.c[q.a]).length===1));
ok("49 distractor misconception",replaced.every(q=>q.c.every((_,i)=>i===q.a||!!q.mis[i])));
ok("50 transfer sibling",replaced.every(q=>typeof q.sibling_group==="string"&&q.sibling_group.includes("-transfer")));
ok("51 curriculum levels preserved",replaced.every(q=>q.school_grade&&EIKEN_LEVELS.includes(q.eiken_level)));
const vocabImproved=bank.filter(q=>q.type==="vocab"&&q.quality_revision==="v0.8.2");
ok("52 vocab improved 60",vocabImproved.length===60);
ok("53 vocab semantic distractors",vocabImproved.every(q=>q.distractor_quality==="semantic"&&new Set(q.c).size===4));
ok("54 no generic vocab distractor set",vocabImproved.every(q=>!(q.c.includes("難しい")&&q.c.includes("静かな")&&q.c.includes("危険な"))));
const vocabTransfer=vocabImproved.filter(q=>q.transfer_check);
ok("55 vocab context transfer 20",vocabTransfer.length===20);
ok("56 vocab context schema",vocabTransfer.every(q=>q.question_type==="context_mcq"&&q.sibling_group.includes("context-transfer")));
ok("57 vocab content-bound review",vocabImproved.every(q=>AI_REVIEW[q.id].reviewedContent===JSON.stringify(q)));
const diagnosticSkills={grammar_infinitive:"infinitive_form",grammar_gerund:"gerund_form",grammar_comparison:"comparison_form",grammar_passive:"passive_form"};
const diagnosticGrammar=bank.filter(q=>diagnosticSkills[q.skill]);
ok("58 grammar diagnostic coverage",diagnosticGrammar.length>0&&diagnosticGrammar.every(q=>q.diagnostic_revision==="v0.8.3"));
ok("59 grammar specific misconception",diagnosticGrammar.every(q=>q.c.every((_,i)=>i===q.a||q.mis[i]===diagnosticSkills[q.skill])));
ok("60 no generic tense tag on diagnostic skills",diagnosticGrammar.every(q=>!(q.mis||[]).includes("tense_confusion")));
ok("61 skill tree diagnostic tags",Object.entries(diagnosticSkills).every(([skill,mis])=>SKILL_TREE.find(s=>s.id===skill).misconceptions.includes(mis)));
ok("62 grammar content-bound review",diagnosticGrammar.every(q=>AI_REVIEW[q.id].reviewedContent===JSON.stringify(q)));
const changed={...bank[0],q:"changed prompt"};
ok("63 changed content invalidates review",reviewForQuestion(changed).stale&&reviewForQuestion(changed).humanRequired);
ok("64 new question requires review",reviewForQuestion({...bank[0],id:"new-question"}).stale);
ok("65 round2 covers current content",bank.every(q=>AI_REVIEW[q.id].reviewer==="AI-v0.9-editorial-round2"&&!AI_REVIEW[q.id].stale));
ok("66 ambiguous items flagged",["g8","v41","v53","v60"].every(id=>AI_REVIEW[id].status==="REVISE"&&AI_REVIEW[id].findings.some(f=>f.area==="answer")));
ok("67 editorial checklist complete",bank.every(q=>Object.keys(AI_REVIEW[q.id].checks).length===9));
ok("68 coverage conservation",SKILL_COVERAGE.reduce((n,s)=>n+s.total,0)===bank.length&&SKILL_COVERAGE.every(s=>s.total===s.base+s.transfer&&s.total===s.keep+s.revise+s.replace));
ok("69 gaps exposed",SKILL_COVERAGE.filter(s=>!s.total).length===7&&["vocab_school","vocab_feeling"].every(id=>SKILL_COVERAGE.find(s=>s.id===id).total===1));
ok("70 transfer not certified by flag",SKILL_COVERAGE.every(s=>s.verifiedTransferPairs===0));
ok("71 coverage reacts to removal",analyzeSkillCoverage(bank.filter(q=>q.id!=="v5")).find(s=>s.id==="vocab_school").total===0);
ok("72 summaries equal item decisions",Object.values(REVIEW_SUMMARY).reduce((a,b)=>a+b,0)===bank.length&&Object.entries(REVIEW_SUMMARY).every(([k,n])=>bank.filter(q=>AI_REVIEW[q.id].status===k).length===n));
const changedChoices={...bank[0],c:[...bank[0].c].reverse()};
ok("73 changed choices invalidate review",reviewForQuestion(changedChoices).stale);
ok("74 diagnostics inside review signature",reviewForQuestion({...bank[0],mis:[]}).stale);
ok("75 review finding schema",bank.every(q=>AI_REVIEW[q.id].findings.every(f=>f.area&&f.severity&&f.evidence&&f.action)));

const initialIsland=islandGrowthView(defaultState()),matureIsland=islandGrowthView({...defaultState(),stars:360,mastery:{vocab:80,grammar:60,listening:40,reading:100}});
ok("76 island changes with earned stars",initialIsland.decorations===0&&matureIsland.decorations===12&&matureIsland.stage>initialIsland.stage);
ok("77 every completed quest adds visible progress",islandGrowthView({...defaultState(),stars:30}).decorations===1);
ok("78 four facility visuals use their own mastery",matureIsland.facilities.garden.level===5&&matureIsland.facilities.workshop.level===4&&matureIsland.facilities.music.level===3&&matureIsland.facilities.library.level===6);
ok("79 existing stars restored on reload",islandGrowthView(engineMigrate({...s,stars:240})).level===3);
ok("80 next island threshold",islandGrowthView({...s,stars:119}).remaining===1&&islandGrowthView({...s,stars:120}).remaining===120);
ok("81 island renderer reaches both scenes",typeof renderIslandGrowth==='function');
const islandInput=JSON.stringify(s);islandGrowthView(s);ok("82 growth view preserves learning record",JSON.stringify(s)===islandInput);
console.table(R);const passed=R.filter(x=>x.pass).length,all=R.every(x=>x.pass);console.log("RESULT",passed+"/"+R.length,all?"PASS":"FAIL");if(!all&&typeof process!=="undefined")process.exitCode=1;return R})();
